build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.21
  amd64: ghcr.io/home-assistant/amd64-base:3.21
  i386: ghcr.io/home-assistant/i386-base:3.21
  # See https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/pull/652#issuecomment-2448119395 why 3.18 is used
  armhf: ghcr.io/home-assistant/armhf-base:3.18
  armv7: ghcr.io/home-assistant/armv7-base:3.18
